# SCCSID: @(#)Makefile	3.0	(ULTRIX-11)	5/21/86
#
######################################################################
#   Copyright (c) Digital Equipment Corporation 1984, 1985, 1986.    #
#   All Rights Reserved. 					     #
#   Reference "/usr/src/COPYRIGHT" for applicable restrictions.      #
######################################################################
#
# This is just a dummy makefile. The real one, "makefile", is
# created automatically by the make in '..'.

SOURCES = ovhndlr.s csv.s doprnt.s setjmp.s signal.s

sources: $(SOURCES)

.DEFAULT:
	sccs get $<
